"""Init

Revision ID: 75dab872e82b
Revises: 
Create Date: 2023-02-25 19:05:46.473426

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '75dab872e82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vk_user',
        sa.Column('vk_id', sa.BIGINT(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('number', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('vk_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_user')
    # ### end Alembic commands ###
