name: Python package

on:
  pull_request:


jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt
      - name: Build coverage file
        run: |
          pytest --showlocals --cache-clear --cov=src tests > pytest-coverage.txt
      - name: Print report
        if: always()
        run: |
          cat pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt requirements.dev.txt"
      - uses: psf/black@stable
      - name: Comment if linting failed
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :poop: Code linting failed, use `black` and `isort` to fix it.

